name: Release

on:
  push:
    tags:
      - "*"

jobs:
  call:
    uses: alexkater/reusable-workflows/.github/workflows/release-with-ai-notes.yml@62d7da0038beae94d3a6dd544fbec2a7c79c0179
    with:
      tag: ${{ github.ref_name }}
      model: openai/gpt-4o
      audience_language: es
